---
title: "BTK and GSEA analysis"
author: "Kindle Zhang qz2527"
date: "2024-12-20"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
# setwd("./data_file")
library(tidyverse)
library(BiocManager)
```


# make a DEG according to BTK gene expression

```{r}
library(DESeq2)
counts_01A = read.table(
  "./data_file/counts01A.txt",
  sep = "\t",
  row.names = 1,
  check.names = F,
  stringsAsFactors = F,
  header = T
)
exp = read.table(
  "./data_file/tpms01A_log2.txt",
  sep = "\t",
  row.names = 1,
  check.names = F,
  header = T
)
identical(colnames(counts_01A),colnames(exp))
gene = "BTK"
med = median(as.numeric(exp[gene, ]))

conditions =
  data.frame(sample = colnames(exp),
             group = factor(ifelse(exp[gene,] > med, "high", "low"), levels = c("low", "high"))) |>
  column_to_rownames("sample")

dds = DESeqDataSetFromMatrix(countData = counts_01A,
                             colData = conditions,
                             design = ~ group)
# dds = DESeq(dds)
# resultsNames(dds)

# res = results(dds)
# save(res,file="./data_file/DEG_BTK.Rda")
```

```{r}
load("./data_file/DEG_BTK.Rda")
```
