---
title: "BTK gene expression difference between two groups"
author: "Kindle Zhang qz2527"
date: "2024-12-20"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
# setwd("./data_file")
library(tidyverse)
library(BiocManager)
```

We select "BTK" gene among four common genes to make a further study

# gene BTK expression difference in cancer and no cancer samples

## boxplot in different samples

```{r}
tpms01A_log2 = read.table(
  "./data_file/tpms01A_log2.txt",
  sep = "\t",
  row.names = 1,
  check.names = F,
  stringsAsFactors = F,
  header = T
)
tpms11A_log2 = read.table(
  "./data_file/tpms11A_log2.txt",
  sep = "\t",
  row.names = 1,
  check.names = F,
  stringsAsFactors = F,
  header = T
)
gene = "BTK"
a = tpms01A_log2[gene, ]
b = tpms11A_log2[gene, ]
a = a |>  t() |>  as.data.frame()
b = b |>  t() |>  as.data.frame()
# write.csv(a, file = "./data_file/BTK_01A.csv")
# write.csv(b, file = "./data_file/BTK_11A.csv")
a = a |>
  mutate(group = "tumor")
rownames(a) = NULL

b = b |>
  mutate(group = "normal")
rownames(b) = NULL
final = rbind(b, a)

final |> ggplot(aes(x = group, y = BTK)) + 
  geom_boxplot() + 
  theme_classic() + 
  labs(title = "BTK expression(TPMS_log2)", x = "group", y = "BTK")
```

## pair plot in common sample

```{r}
tpms01A_log2 = tpms01A_log2 |>  t() |>  as.data.frame()
tpms11A_log2 = tpms11A_log2 |>  t() |>  as.data.frame()
rownames(tpms01A_log2) = substring(rownames(tpms01A_log2), 1, 12)
rownames(tpms11A_log2) = substring(rownames(tpms11A_log2), 1, 12)
# 找到来自同一个患者的组织

a = intersect(rownames(tpms01A_log2),rownames(tpms11A_log2)) # 57 patients have both sample with tumor and no tumor
tpms01A_log2 = tpms01A_log2[a,]
tpms11A_log2 = tpms11A_log2[a,]
peidui = cbind(tpms11A_log2[, gene], tpms01A_log2[, gene])#11A放在前面
peidui = as.data.frame(peidui)
colnames(peidui) = c("normal", "tumor")
# write.csv(peidui,file = "./data_file/peidui.csv")
peidui =
  peidui |> 
  mutate(patient = row_number()) |> 
  pivot_longer(cols = c("normal","tumor"), 
               names_to = "group", 
               values_to = "value") |> 
  arrange(group)
```

```{r}
library(ggpubr)
ggplot(peidui,
       aes(
         x = group,
         y = value,
         group = patient,
         color = group
       )) +
  geom_point(size = 3) +
  geom_line(aes(group = patient), color = "black") +
  scale_color_manual(values = c("normal" = "blue", "tumor" = "orange")) +
  theme_classic() +
  labs(title = "Paired Comparison: Normal vs Tumor", y = "BTK Value") +
  theme(legend.position = "none") +
  stat_compare_means(method = "t.test", aes(group = group), label = "p.signif")
```

# make an survival analysis according to different BTK expression

## survival analysis In 01A sample

```{r}
# dichotomize the BTK expression
surv = read.table(
  "./data_file/exp_surv_01A.txt",
  sep = "\t",
  row.names = 1,
  check.names = F,
  stringsAsFactors = F,
  header = T
)
surv$OS.time = surv$OS.time / 365
```

```{r}
library(survival)
# median 
# BTK
surv$group = ifelse(surv$BTK > median(surv$BTK), "High", "Low")
class(surv$group)
surv$group = factor(surv$group, levels = c("Low", "High")) 
class(surv$group)
table(surv$group)
fitd = survdiff(Surv(OS.time, OS) ~ group,
                data      = surv,
                na.action = na.exclude)
pValue = 1 - pchisq(fitd$chisq, length(fitd$n) - 1)
```

## plot survival curve

```{r}
fit = survfit(Surv(OS.time, OS) ~ group, data = surv)
summary(fit)
p.lab = paste0("P", ifelse(pValue < 0.001, " < 0.001", paste0(" = ", round(pValue, 3))))

library(survminer)
ggsurvplot(
  fit,
  data = surv,
  pval = p.lab,
  conf.int = TRUE,
  # 显示置信区间
  risk.table = TRUE,
  # 显示风险表
  risk.table.col = "strata",
  palette = "jco",
  # 配色采用jco
  legend.labs = c("Low", "High"),
  # 图例
  size = 1,
  xlim = c(0, 20),
  # x轴长度
  break.time.by = 5,
  # x轴步长为5
  legend.title = "BTK",
  surv.median.line = "hv",
  # 限制垂直和水平的中位生存
  ylab = "Survival probability (%)",
  # 修改y轴标签
  xlab = "Time (Years)",
  # 修改x轴标签
  ncensor.plot = TRUE,
  # 显示删失图块
  ncensor.plot.height = 0.25,
  risk.table.y.text = FALSE
)
```

## different expression of BTK in different stages

```{r}
clinical.expr01A = read.table(
  "./data_file/clinical.expr01A.txt",
  sep = "\t",
  row.names = 1,
  check.names = F,
  stringsAsFactors = F,
  header = T
)
gene = "BTK"
clinical_BTK =
  cbind(clinical.expr01A[, 1:6], clinical.expr01A[, gene])
# write.csv(clinical_BTK, file = "./data_file/clinical_BTK.csv")
```

```{r}
plot_boxplot_by_group <- function(data, x, y) {
  # 筛选数据
  filtered_data <- data %>%
    filter(!is.na(.data[[x]])) %>%
    mutate(factor_var = as.factor(.data[[x]]))
  
  # 画图
  p <- ggplot(filtered_data,
              aes(x = factor_var, y = .data[[y]], fill = factor_var)) +
    geom_boxplot() +
    labs(
      title = paste0("BTK expression change by ", sub(".*_", "" , x)),
      y = "BTK expression",
      x = x
    ) +
    theme_minimal() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
      legend.position = "none"
    )
  
  # Kruskal-Wallis 检验
  k_result <- kruskal.test(filtered_data[[y]] ~ filtered_data$factor_var)

  # 返回图和检验结果
  return(list(plot = p, test = k_result))
}
```

```{r}
library(purrr)

x_vars <- colnames(clinical_BTK)[3:6]
y_vars <- colnames(clinical_BTK)[7]

var_combinations <- expand.grid(x = x_vars, y = y_vars, stringsAsFactors = FALSE)

pmap(var_combinations, function(x, y) {
  plot_boxplot_by_group(data = clinical_BTK, x = x, y = y)
})
```

