---
title: "TCGA LUDA clinical"
author: "Kindle Zhang qz2527"
date: "2024-12-20"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
# setwd("./data_file")
library(tidyverse)
library(BiocManager)
```

```{r}
load("./data_file/luad.gdc_2022.rda")

# 随着肿瘤分期的进展
clinical <- as.data.frame(expquery2@colData)  # extract clinical data
clinical = clinical[!duplicated(clinical$sample), ]

clinical <-
  clinical[, c(
    "gender",
    "age_at_index",
    "ajcc_pathologic_stage",
    "ajcc_pathologic_t",
    "ajcc_pathologic_n",
    "ajcc_pathologic_m"
  )]

# stage means tumor stage, t 原发肿瘤大小或范围, n 区域淋巴结受累情况 ，m 远处转移。

class(clinical$gender)
class(clinical$age_at_index)
class(clinical$ajcc_pathologic_stage)
class(clinical$ajcc_pathologic_t)
class(clinical$ajcc_pathologic_n)
class(clinical$ajcc_pathologic_m)

table(clinical$gender)
table(clinical$age_at_index)
table(clinical$ajcc_pathologic_stage)
table(clinical$ajcc_pathologic_t)
table(clinical$ajcc_pathologic_n)
table(clinical$ajcc_pathologic_m)

# gsub = replace
clinical$ajcc_pathologic_stage <-
  gsub("A", "", clinical$ajcc_pathologic_stage)
clinical$ajcc_pathologic_stage <-
  gsub("B", "", clinical$ajcc_pathologic_stage)
clinical$ajcc_pathologic_t <-
  gsub("a", "", clinical$ajcc_pathologic_t)
clinical$ajcc_pathologic_t <-
  gsub("b", "", clinical$ajcc_pathologic_t)
clinical$ajcc_pathologic_m <-
  gsub("a", "", clinical$ajcc_pathologic_m)
clinical$ajcc_pathologic_m <-
  gsub("b", "", clinical$ajcc_pathologic_m)

#提取01A临床数据
rownames(clinical) <- substring(rownames(clinical),1,16)

##将基因表达谱和临床数据合并并保存
exp01A <-
  read.table(
    "./data_file/tpms01A_log2.txt",
    sep = "\t",
    row.names = 1,
    check.names = F,
    stringsAsFactors = F,
    header = T
  )

clinical01A <- clinical[colnames(exp01A), ]
exp01A <- exp01A  |>  t()  |>  as.data.frame()
identical(rownames(clinical01A),rownames(exp01A))
clinical.expr01A <- cbind(clinical01A, exp01A)

# write.table(
#   clinical.expr01A,
#   "./data_file/clinical.expr01A.txt",
#   sep = "\t",
#   row.names = T,
#   col.names = NA,
#   quote = F
# )

ESTIMATE_result <-
  read.table(
    "./data_file/ESTIMATE_result.txt",
    sep = "\t",
    row.names = 1,
    check.names = F,
    stringsAsFactors = F,
    header = T
  )
identical(rownames(clinical01A), rownames(ESTIMATE_result))

clinical.ESTIMATE_result01A <- cbind(clinical01A, ESTIMATE_result)

# write.csv(clinical.ESTIMATE_result01A, 
# file = "./data_file/clinical.ESTIMATE_result01A.csv")
```

We can get a data combined with estimate score and clinical data. 

```{r}
clinical.ESTIMATE_result01A |>
  filter(!is.na(ajcc_pathologic_stage)) |> 
  ggplot(aes(x = ajcc_pathologic_stage,
             y = ImmuneScore,
             fill = ajcc_pathologic_stage)) +
  geom_boxplot() +
  labs(title = "Stage",
       y = "Immune Score") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
    legend.position = NULL
  )
```

calculate p-value

```{r}
test = 
clinical.ESTIMATE_result01A |>
  filter(!is.na(ajcc_pathologic_stage)) |>
  mutate(ajcc_pathologic_stage = as.factor(ajcc_pathologic_stage)) %>%  
  kruskal.test(ImmuneScore ~ ajcc_pathologic_stage)
  
test
```